'use client';

import { FormEvent, useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { Bell, Bot, Bookmark, Check, ChevronRight, ExternalLink, FileText, Globe2, Heart, Home, LoaderCircle, Map, Menu, Search, ShieldCheck, Sparkles, UserRound, X, type LucideIcon } from 'lucide-react';
import { languages, ui } from '../lib/i18n';

const API=process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000/api';
type Scheme={id:string;name:string;description:string;category:string;benefits:string[];official_url:string;application_url:string|null;documents:{name:string;description:string}[];government_level?:string;state_ut?:string;scheme_service_type?:string;department?:string;verification_status?:string;last_verified_date?:string};
type Guide={steps:{id:string;step_number:number;title:string;instruction:string}[]};
const profile={occupation:'Student',preferred_language:'en'};
const call=(path:string,init?:RequestInit)=>fetch(API+path,init).then(async r=>{if(!r.ok)throw Error();return r.json()});
const go=(to:string)=>{history.pushState({},'',to);dispatchEvent(new PopStateEvent('popstate'))};

export default function Portal(){
 const [path,setPath]=useState('/'),[lang,setLang]=useState('en'),[schemes,setSchemes]=useState<Scheme[]>([]),[query,setQuery]=useState(''),[level,setLevel]=useState(''),[stateUt,setStateUt]=useState(''),[recordType,setRecordType]=useState(''),[stateOptions,setStateOptions]=useState<{name:string;government_level:string}[]>([]),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[saved,setSaved]=useState<string[]>([]),[guide,setGuide]=useState<Guide|null>(null),[guideScheme,setGuideScheme]=useState<Scheme|null>(null),[menu,setMenu]=useState(false);
 const t=ui[lang]||ui.en;
 useEffect(()=>{const f=()=>setPath(location.pathname);f();addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);
 useEffect(()=>{const l=localStorage.getItem('pn-language');if(l&&ui[l])setLang(l);const s=localStorage.getItem('pn-saved');if(s)setSaved(JSON.parse(s))},[]);
 useEffect(()=>{call('/catalogue/filters').then(x=>setStateOptions(x.data.state_uts||[])).catch(()=>{})},[]);
 useEffect(()=>{setLoading(true);setFailed(false);const params=new URLSearchParams({q:query});if(level)params.set('government_level',level);if(stateUt)params.set('state_ut',stateUt);if(recordType)params.set('scheme_service_type',recordType);call('/schemes?'+params).then(x=>setSchemes(x.data||[])).catch(()=>setFailed(true)).finally(()=>setLoading(false))},[query,level,stateUt,recordType]);
 const language=(v:string)=>{setLang(v);localStorage.setItem('pn-language',v)};
 const save=(id:string)=>setSaved(old=>{const next=old.includes(id)?old.filter(x=>x!==id):[...old,id];localStorage.setItem('pn-saved',JSON.stringify(next));return next});
 const openGuide=async(s:Scheme)=>{setGuideScheme(s);try{setGuide((await call('/navigator/'+s.id)).data)}catch{setGuide({steps:[]})}};
 const id=path.match(/^\/(?:schemes|eligibility|documents)\/([^/]+)/)?.[1],scheme=schemes.find(s=>s.id===id)||guideScheme;
 if(path==='/')return <Splash t={t}/>;
 if(path==='/onboarding')return <Onboarding t={t}/>;
 if(path.startsWith('/admin'))return <Forbidden t={t}/>;
 if(path==='/language')return <Language t={t} lang={lang} choose={language}/>;
 return <main><Header t={t} lang={lang} choose={language} menu={menu} setMenu={setMenu} path={path}/><div className="layout"><Sidebar t={t} path={path}/><section className="content">
  {path==='/copilot'?<Copilot t={t} lang={lang}/>:path==='/recommendations'?<Recommendations t={t} lang={lang}/>:path==='/saved'?<Saved t={t} schemes={schemes.filter(s=>saved.includes(s.id))} save={save} openGuide={openGuide}/>:scheme?<Details t={t} scheme={scheme} mode={path.split('/')[1]} save={save} saved={saved.includes(scheme.id)} openGuide={openGuide}/>:<Directory t={t} schemes={schemes} query={query} setQuery={setQuery} level={level} setLevel={setLevel} stateUt={stateUt} setStateUt={setStateUt} stateOptions={stateOptions} recordType={recordType} setRecordType={setRecordType} loading={loading} failed={failed} saved={saved} save={save} openGuide={openGuide} path={path}/>}
 </section></div><Mobile t={t} path={path}/><AnimatePresence>{guide&&guideScheme&&<Navigator t={t} scheme={guideScheme} guide={guide} close={()=>setGuide(null)}/>}</AnimatePresence></main>
}
function Brand(){return <button className="brand" onClick={()=>go('/dashboard')}><span><Sparkles size={16}/></span>PRAGYA<strong>NAGARIK</strong><small>AI</small></button>}
const items:[string,string,LucideIcon][]=[['/dashboard','home',Home],['/schemes','schemes',Search],['/recommendations','recommendations',Sparkles],['/copilot','assistant',Bot],['/saved','saved',Bookmark]];
function Header({t,lang,choose,menu,setMenu,path}:any){return <header><Brand/><nav>{items.slice(1,3).map(([to,k])=><button key={to} onClick={()=>go(to)}>{t[k]}</button>)}<button className="ask" onClick={()=>go('/copilot')}><Sparkles size={14}/>{t.ask}</button></nav><div className="actions"><label><Globe2 size={16}/><select value={lang} aria-label={t.language} onChange={e=>choose(e.target.value)}>{languages.map(([id,n])=><option value={id} key={id}>{n}</option>)}</select></label><button className="icon"><Bell size={18}/></button><button className="avatar"><UserRound size={17}/></button><button className="hamburger" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div>{menu&&<div className="menu">{items.map(([to,k])=><button key={to} className={path===to?'active':''} onClick={()=>{go(to);setMenu(false)}}>{t[k]}</button>)}</div>}</header>}
function Sidebar({t,path}:any){return <aside><p>{t.portal}</p>{items.map(([to,k,Icon])=><button key={to} className={path===to||(to!=='/'&&path.startsWith(to))?'active':''} onClick={()=>go(to)}><Icon size={18}/>{t[k]}</button>)}<div className="trust"><ShieldCheck size={18}/><span><b>Verified information</b>Always check the official source.</span></div></aside>}
function Mobile({t,path}:any){return <div className="mobile">{items.map(([to,k,Icon])=><button key={to} className={path===to?'active':''} onClick={()=>go(to)}><Icon size={18}/><small>{t[k]}</small></button>)}</div>}
function Directory({t,schemes,query,setQuery,level,setLevel,stateUt,setStateUt,stateOptions,recordType,setRecordType,loading,failed,saved,save,openGuide,path}:any){
 const home=path==='/dashboard',shown=home?schemes.slice(0,3):schemes;
 return <><section className="hero"><div><em><Sparkles size={13}/>{t.tagline}</em><h1>{home?t.title:t.find}</h1><p>{home?t.subtitle:'Search verified central, state and Union Territory records.'}</p><div className="search"><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/>{query&&<button onClick={()=>setQuery('')}><X size={16}/></button>}</div></div><div className="orb"><Bot size={48}/><small>AI guidance</small></div></section>
 {!home&&<div className="catalogue-filters"><select value={level} onChange={e=>{setLevel(e.target.value);setStateUt('')}} aria-label="Government level"><option value="">All government levels</option><option value="CENTRAL">Central Government</option><option value="STATE">State Government</option><option value="UT">Union Territory</option></select><select value={stateUt} onChange={e=>setStateUt(e.target.value)} aria-label="State or Union Territory"><option value="">All States and UTs</option>{stateOptions.filter((x:any)=>!level||x.government_level===level).map((x:any)=><option key={x.name} value={x.name}>{x.name}</option>)}</select><select value={recordType} onChange={e=>setRecordType(e.target.value)} aria-label="Record type"><option value="">Schemes and services</option><option value="SCHEME">Schemes</option><option value="SERVICE">Services</option></select></div>}
 {home&&<div className="quick"><Quick icon={Bot} text={t.ask} go={()=>go('/copilot')}/><Quick icon={Search} text={t.find} go={()=>go('/schemes')}/><Quick icon={FileText} text={t.eligibility} go={()=>go('/recommendations')}/><Quick icon={Map} text={t.guide} go={()=>schemes[0]&&openGuide(schemes[0])}/></div>}<div className="heading"><div><em className="plain">{home?'PERSONALISED DISCOVERY':t.directory}</em><h2>{home?t.recommended:t.schemes}</h2></div><small>{t.demo}</small></div>{loading?<State t={t} type="load"/>:failed?<State t={t} type="error"/>:shown.length?<div className="cards">{shown.map((s:Scheme,i:number)=><Card t={t} key={s.id} scheme={s} match={home?95-i*11:undefined} saved={saved.includes(s.id)} save={save} openGuide={openGuide}/>)}</div>:<State t={t} type="empty"/>}</>}
function Quick({icon:Icon,text,go:click}:any){return <button onClick={click}><span><Icon size={19}/></span><b>{text}</b><ChevronRight size={16}/></button>}
function Card({t,scheme,match,saved,save,openGuide}:any){return <motion.article whileHover={{y:-3}}><div className="cardtop"><span className="pill">{scheme.category}</span><button className={saved?'heart selected':'heart'} onClick={()=>save(scheme.id)}><Heart size={18} fill={saved?'currentColor':'none'}/></button></div><h3>{scheme.name}</h3><p>{scheme.description}</p><small className="catalogue-meta">{scheme.government_level}{scheme.state_ut?` · ${scheme.state_ut}`:''}{scheme.last_verified_date?` · Verified ${scheme.last_verified_date}`:''}</small>{match&&<div className="match"><b>{match}% {t.match}</b><small>{t.matchHint}</small></div>}<div className="cardactions"><button onClick={()=>go('/schemes/'+scheme.id)}>{t.details}<ChevronRight size={15}/></button><button onClick={()=>openGuide(scheme)}><Map size={14}/>{t.guide}</button></div><a href={scheme.official_url} target="_blank" rel="noreferrer"><ShieldCheck size={13}/>{t.official}<ExternalLink size={11}/></a></motion.article>}
function Copilot({t,lang}:any){const [messages,setMessages]=useState<any[]>([]),[value,setValue]=useState(''),[busy,setBusy]=useState(false);const send=async(e?:FormEvent)=>{e?.preventDefault();if(!value.trim()||busy)return;let text=value;setMessages(m=>[...m,{user:true,text}]);setValue('');setBusy(true);try{const r=await call('/copilot/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,profile:{...profile,preferred_language:lang}})});setMessages(m=>[...m,{text:r.data.answer,note:r.data.verification_note}])}catch{setMessages(m=>[...m,{text:t.aiError}])}finally{setBusy(false)}};return <section className="copilot"><div className="copilot-title"><span><Bot/></span><div><em className="plain">{t.copilot}</em><h1>{t.askTitle}</h1><p>{t.askSub}</p></div></div><div className="chat"><div className="messages">{!messages.length&&<div className="starter"><Sparkles/><h2>{t.askTitle}</h2><p>{t.askSub}</p>{[t.suggest1,t.suggest2,t.suggest3].map(x=><button key={x} onClick={()=>setValue(x)}>{x}</button>)}</div>}{messages.map((m,i)=><div key={i} className={m.user?'message user':'message'}><span>{m.user?<UserRound size={15}/>:<Bot size={15}/>}</span><div>{m.text}{m.note&&<small><ShieldCheck size={12}/>{m.note}</small>}</div></div>)}{busy&&<div className="message"><span><Bot size={15}/></span><div className="dots">•••</div></div>}</div><form onSubmit={send}><input value={value} onChange={e=>setValue(e.target.value)} placeholder={t.placeholder}/><button disabled={!value.trim()||busy}><ChevronRight size={20}/></button></form><small className="note"><ShieldCheck size={13}/>{t.aiNote}</small></div></section>}
function Recommendations({t,lang}:any){const [data,setData]=useState<any[]>([]),[loading,setLoading]=useState(true);useEffect(()=>{call('/recommendations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...profile,preferred_language:lang})}).then(x=>setData(x.data)).catch(()=>setData([])).finally(()=>setLoading(false))},[lang]);return <><div className="title"><em className="plain">{t.personalised}</em><h1>{t.recommendations}</h1><p>{t.recommendSub}</p></div>{loading?<State t={t} type="load"/>:<div className="recommendations">{data.map(x=><article key={x.scheme.id}><div className="score">{x.match_score}%<small>{t.match}</small></div><div><span className="pill">{x.scheme.category}</span><h2>{x.scheme.name}</h2><p>{x.scheme.description}</p><ul>{x.why.map((w:string)=><li key={w}><Check size={14}/>{w}</li>)}</ul></div><button onClick={()=>go('/eligibility/'+x.scheme.id)}>{t.check}<ChevronRight size={15}/></button></article>)}</div>}</>}
function Details({t,scheme,mode,save,saved,openGuide}:any){const [data,setData]=useState<any>(null),[loading,setLoading]=useState(mode==='eligibility');useEffect(()=>{if(mode==='eligibility')call('/eligibility/'+scheme.id,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(profile)}).then(x=>setData(x.data)).finally(()=>setLoading(false))},[mode,scheme.id]);return <><section className="detail"><div><span className="pill">{scheme.category}</span><span className="official"><ShieldCheck size={14}/>{t.official}</span><h1>{mode==='documents'?t.documents:scheme.name}</h1><p>{mode==='documents'?t.documentsSub:scheme.description}</p></div><div><button onClick={()=>save(scheme.id)}><Heart size={17} fill={saved?'currentColor':'none'}/>{saved?t.saved:t.save}</button><a href={scheme.application_url} target="_blank" rel="noreferrer">{t.open}<ExternalLink size={15}/></a></div></section>{mode==='eligibility'?(loading?<State t={t} type="load"/>:<Eligibility t={t} data={data} docs={scheme.documents}/>):<div className="details">{mode!=='documents'&&<><article><h2>{t.benefits}</h2><List items={scheme.benefits}/></article><article><h2>{t.who}</h2><p>{t.why}</p><button className="primary" onClick={()=>go('/eligibility/'+scheme.id)}>{t.check}<ChevronRight size={15}/></button></article></>}<article className="wide"><h2>{t.documents}</h2><Documents docs={scheme.documents}/></article><article className="wide guidebox"><Map/><div><h2>{t.needGuide}</h2><p>{t.guideSub}</p></div><button className="primary" onClick={()=>openGuide(scheme)}>{t.guide}<ChevronRight size={15}/></button></article></div>}</>}
function Eligibility({t,data,docs}:any){if(!data)return <State t={t} type="error"/>;return <div className="eligibility"><div className="circle">{data.score}%<small>{t.profileMatch}</small></div><div><span className="status"><Check size={14}/>{data.status}</span><h2>{t.assessment}</h2><p>{data.explanation}</p></div><div className="conditions"><div><h3>{t.matched}</h3><List items={data.matched_conditions}/></div><div><h3>{t.missing}</h3><List items={data.missing_information}/></div></div><Documents docs={data.required_documents||docs}/></div>}
function List({items}:any){return <ul className="list">{items.length?items.map((x:string)=><li key={x}><Check size={15}/>{x}</li>):<li>—</li>}</ul>}
function Documents({docs}:any){return <div className="docs">{docs.map((d:any)=><div key={d.name}><span><FileText size={18}/></span><p><b>{d.name}</b>{d.description}</p><Check size={17}/></div>)}</div>}
function Saved({t,schemes,save,openGuide}:any){return <><div className="title"><em className="plain">YOUR SAVED LIST</em><h1>{t.saved}</h1></div>{schemes.length?<div className="cards">{schemes.map((s:Scheme)=><Card key={s.id} scheme={s} t={t} saved save={save} openGuide={openGuide}/>)}</div>:<State t={t} type="empty"/>}</>}
function Navigator({t,scheme,guide,close}:any){return <motion.div className="modal" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section initial={{y:25}} animate={{y:0}} exit={{y:25}}><button className="close" onClick={close}><X/></button><em className="plain"><Map size={13}/>{t.navigator}</em><h2>{scheme.name}</h2><p>{t.navigatorSub}</p><div className="steps">{guide.steps.map((s:any)=><div key={s.id}><span>{s.step_number}</span><p><b>{s.title}</b>{s.instruction}</p></div>)}</div><a className="primary" href={scheme.application_url} target="_blank" rel="noreferrer">{t.open}<ExternalLink size={15}/></a></motion.section></motion.div>}
const entryCss='.splash,.onboarding{min-height:100vh;background:radial-gradient(circle at 75% 20%,#d9e5ff 0,#f8fbff 34%,#eef2ff 100%);display:grid;place-items:center;padding:24px}.splash>div{text-align:center;animation:rise .55s ease-out}.splash span,.onboard-icon{width:75px;height:75px;margin:auto;display:grid;place-items:center;border-radius:24px;color:#fff;background:linear-gradient(135deg,#1954c7,#7258d8);box-shadow:0 18px 40px #3159a644}.splash h1{font-size:34px;margin:20px 0 7px}.splash h1 b{color:#7258d8}.splash p,.onboarding p{color:#62718a;font-size:14px;margin:0}.splash button{margin-top:25px;border:0;background:transparent;color:#1954c7;font-weight:700;display:inline-flex;gap:3px;align-items:center}.onboarding{display:block}.onboarding .brand{position:absolute;top:28px;left:max(28px,calc((100vw - 1120px)/2))}.onboarding section{max-width:600px;margin:15vh auto;text-align:center;background:#fff;border:1px solid #e5ebf3;border-radius:24px;padding:44px;box-shadow:0 20px 55px #1b3f7820}.dots-nav{display:flex;justify-content:center;gap:6px;margin:25px 0 12px}.dots-nav i{width:7px;height:7px;border-radius:99px;background:#d4ddea}.dots-nav i.active{background:#1954c7;width:22px}.onboarding h1{font-size:29px;margin:12px}.onboarding p{line-height:1.55;margin:0 auto;max-width:420px}.onboard-actions{display:flex;justify-content:space-between;margin-top:32px}.skip{border:0;background:none;color:#62718a;font-size:13px}.onboard-actions .primary{padding:11px 14px}@keyframes rise{from{opacity:0;transform:translateY(12px)}to{opacity:1;transform:none}}';
function Splash({t}:any){useEffect(()=>{const timer=setTimeout(()=>go('/onboarding'),3000);return()=>clearTimeout(timer)},[]);return <><style>{entryCss}</style><main className="splash"><div><img src="/assets/pragyanagrik-logo.jpeg" alt="PragyaNagrik — Democratizing Intelligence for Every Citizen" style={{width:'min(310px,78vw)',height:'auto',borderRadius:24,boxShadow:'0 18px 45px #173e7a26'}}/><p>{t.tagline}</p></div></main></>}
function Onboarding({t}:any){const [step,setStep]=useState(0);const slides:[string,string,LucideIcon][]=[['Government services, made simple.','Find verified schemes, documents and official links without the confusion.',Search],['Intelligence in your language.','Choose a language preference for a clearer, more personal experience.',Globe2],['Guidance when you need it.','Ask PragyaNagarik AI and follow official application steps carefully.',Bot]];const [title,text,Icon]=slides[step];return <><style>{entryCss}</style><main className="onboarding"><Brand/><section><span className="onboard-icon"><Icon size={35}/></span><div className="dots-nav">{slides.map((_,i)=><i key={i} className={i===step?'active':''}/>)}</div><h1>{title}</h1><p>{text}</p><div className="onboard-actions"><button className="skip" onClick={()=>go('/language')}>Skip</button><button className="primary" onClick={()=>step===slides.length-1?go('/language'):setStep(step+1)}>{step===slides.length-1?'Get started':'Next'}<ChevronRight size={16}/></button></div></section></main></>}
function Language({t,lang,choose}:any){return <main className="standalone"><Brand/><section><Globe2/><em className="plain">PERSONALISE YOUR EXPERIENCE</em><h1>{t.choose}</h1><p>{t.chooseSub}</p><div>{languages.map(([id,name])=><button key={id} className={lang===id?'selected':''} onClick={()=>{choose(id);go('/dashboard')}}>{name}<Check size={16}/></button>)}</div></section></main>}
function Forbidden({t}:any){return <main className="standalone"><Brand/><section><ShieldCheck/><em className="plain">{t.access}</em><h1>{t.forbidden}</h1><p>{t.forbiddenSub}</p><button className="primary" onClick={()=>go('/')}>{t.back}</button></section></main>}
function State({t,type}:any){return <div className="state">{type==='load'?<LoaderCircle className="spin"/>:type==='error'?<X/>:<Search/>}<h3>{type==='load'?t.loading:type==='error'?t.error:t.empty}</h3><p>{type==='error'?t.retry:t.emptySub}</p></div>}
