create extension if not exists "uuid-ossp";
create type app_role as enum ('CITIZEN','DEPARTMENT_ADMIN','SUPER_ADMIN');
create table users (id uuid primary key references auth.users(id) on delete cascade, role app_role not null default 'CITIZEN', created_at timestamptz default now());
create table citizen_profiles (user_id uuid primary key references users(id) on delete cascade, name text, state text, district text, age int check(age between 0 and 120), occupation text, education text, annual_income numeric, gender text, category text, preferred_language text not null default 'en', digital_comfort text not null default 'comfortable', updated_at timestamptz default now());
alter table citizen_profiles add column if not exists profile_completed boolean not null default false;
create table departments (id uuid primary key default uuid_generate_v4(), name text not null, official_url text, created_at timestamptz default now());
create unique index if not exists departments_name_unique_idx on departments (name);
create table schemes (id uuid primary key default uuid_generate_v4(), department_id uuid references departments(id), name text not null, description text not null, category text not null, state text, benefits jsonb not null default '[]', eligibility jsonb not null default '{}', official_url text not null, application_url text, processing_time text, information_status text default 'PENDING_VERIFICATION', last_verified_at timestamptz, active boolean default true, created_at timestamptz default now(), updated_at timestamptz default now());
create table jurisdictions (code text primary key, name text not null unique, government_level text not null check (government_level in ('STATE','UT')), is_active boolean not null default true);
alter table schemes add column if not exists scheme_service_type text not null default 'SCHEME' check (scheme_service_type in ('SCHEME','SERVICE'));
alter table schemes add column if not exists government_level text not null default 'CENTRAL' check (government_level in ('CENTRAL','STATE','UT'));
alter table schemes add column if not exists state_ut_code text references jurisdictions(code);
alter table schemes add column if not exists verification_status text not null default 'PENDING_ADMIN_REVIEW' check (verification_status in ('OFFICIAL_SOURCE','PENDING_ADMIN_REVIEW','REJECTED','ARCHIVED'));
alter table schemes add column if not exists reviewed_by uuid references users(id);
alter table schemes add column if not exists reviewed_at timestamptz;
alter table schemes add column if not exists source_reference text;
create index if not exists schemes_catalogue_filter_idx on schemes (government_level, state_ut_code, scheme_service_type, category) where active = true;
create index if not exists schemes_verification_idx on schemes (verification_status, last_verified_at);
create table scheme_documents (id uuid primary key default uuid_generate_v4(), scheme_id uuid references schemes(id) on delete cascade, name text not null, description text, official_alternatives text[] default '{}');
create table scheme_application_steps (id uuid primary key default uuid_generate_v4(), scheme_id uuid references schemes(id) on delete cascade, step_number int not null, title text not null, instruction text not null, screenshot_url text, highlight_x numeric, highlight_y numeric, highlight_width numeric, highlight_height numeric, video_url text, pdf_url text, external_url text);
create table saved_schemes (user_id uuid references users(id) on delete cascade, scheme_id uuid references schemes(id) on delete cascade, created_at timestamptz default now(), primary key(user_id,scheme_id));
create table chat_sessions (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id) on delete cascade, language text default 'en', created_at timestamptz default now());
create table chat_messages (id uuid primary key default uuid_generate_v4(), session_id uuid references chat_sessions(id) on delete cascade, role text check(role in ('user','assistant')), content text not null, created_at timestamptz default now());
create table recent_searches (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id) on delete cascade, query text not null, language text not null, result_count int default 0, created_at timestamptz default now());
create table notifications (id uuid primary key default uuid_generate_v4(), user_id uuid references users(id) on delete cascade, kind text, title text not null, body text not null, read_at timestamptz, created_at timestamptz default now());
create table audit_logs (id uuid primary key default uuid_generate_v4(), actor_id uuid references users(id), action text not null, target_type text, target_id text, metadata jsonb default '{}', created_at timestamptz default now());
alter table citizen_profiles enable row level security;
create policy "own profile" on citizen_profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
alter table saved_schemes enable row level security;
create policy "own saved schemes" on saved_schemes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
