-- Seed only known national schemes; departments must verify regional details before production use.
insert into jurisdictions (code,name,government_level) values
('AP','Andhra Pradesh','STATE'),('AR','Arunachal Pradesh','STATE'),('AS','Assam','STATE'),('BR','Bihar','STATE'),('CG','Chhattisgarh','STATE'),('GA','Goa','STATE'),('GJ','Gujarat','STATE'),('HR','Haryana','STATE'),('HP','Himachal Pradesh','STATE'),('JH','Jharkhand','STATE'),('KA','Karnataka','STATE'),('KL','Kerala','STATE'),('MP','Madhya Pradesh','STATE'),('MH','Maharashtra','STATE'),('MN','Manipur','STATE'),('ML','Meghalaya','STATE'),('MZ','Mizoram','STATE'),('NL','Nagaland','STATE'),('OD','Odisha','STATE'),('PB','Punjab','STATE'),('RJ','Rajasthan','STATE'),('SK','Sikkim','STATE'),('TN','Tamil Nadu','STATE'),('TS','Telangana','STATE'),('TR','Tripura','STATE'),('UP','Uttar Pradesh','STATE'),('UK','Uttarakhand','STATE'),('WB','West Bengal','STATE'),
('AN','Andaman and Nicobar Islands','UT'),('CH','Chandigarh','UT'),('DH','Dadra and Nagar Haveli and Daman and Diu','UT'),('DL','Delhi','UT'),('JK','Jammu and Kashmir','UT'),('LA','Ladakh','UT'),('LD','Lakshadweep','UT'),('PY','Puducherry','UT') on conflict (code) do update set name=excluded.name,government_level=excluded.government_level;
insert into departments (id,name,official_url) values ('00000000-0000-0000-0000-000000000001','Government of India','https://www.india.gov.in/') on conflict do nothing;
insert into schemes (id,department_id,name,description,category,state,benefits,eligibility,official_url,application_url,information_status,last_verified_at) values
('10000000-0000-0000-0000-000000000001','00000000-0000-0000-0000-000000000001','PM-KISAN','Income support scheme for eligible landholding farmer families.','Agriculture','All India','["Income support"]','{"occupations":["Farmer"]}','https://pmkisan.gov.in/','https://pmkisan.gov.in/','OFFICIAL_SOURCE',now()),
('10000000-0000-0000-0000-000000000002','00000000-0000-0000-0000-000000000001','Pradhan Mantri Awas Yojana','Housing assistance programme; refer to the official portal for current eligibility.','Housing','All India','["Housing assistance"]','{}','https://pmaymis.gov.in/','https://pmaymis.gov.in/','OFFICIAL_SOURCE',now()),
('10000000-0000-0000-0000-000000000003','00000000-0000-0000-0000-000000000001','National Scholarship Portal','Single portal for participating scholarship schemes. Individual criteria vary by scholarship.','Education','All India','["Scholarship discovery"]','{"occupations":["Student"]}','https://scholarships.gov.in/','https://scholarships.gov.in/','OFFICIAL_SOURCE',now()),
('10000000-0000-0000-0000-000000000004','00000000-0000-0000-0000-000000000001','PM Mudra Yojana','Credit support through eligible lending institutions for micro enterprises.','Entrepreneurship','All India','["Business credit"]','{"occupations":["Entrepreneur","Worker"]}','https://www.mudra.org.in/','https://www.mudra.org.in/','OFFICIAL_SOURCE',now()) on conflict do nothing;
